export const siteConfig = {
  url: "https://rinkevich.github.io",
  name: "Andrejs Rinkevičs",
  username: "rinkevich",
  firstName: "Andrejs",
  lastName: "Rinkevičs",
  title: "Andrejs Rinkevičs — System Architect & Full-stack Engineer",
  jobTitle: "System Architect & Full-stack Software Engineer",
  description:
    "I turn ideas into production products — defining the architecture and migration path, then building the services and UIs on top. 10+ years, Riga-based.",
  locale: "en_US",
  ogImage: "/og.png",
  twitterCreator: "@rinkevich",
  location: {
    city: "Riga",
    country: "LV",
  },
  sameAs: [
    "https://www.linkedin.com/in/andrejsrinkevics/",
    "https://github.com/rinkevich",
    "https://www.threads.com/@rinkevich",
  ],
  knowsAbout: [
    "Software architecture",
    "Solution architecture",
    "Python",
    "Django",
    "TypeScript",
    "React",
    "Next.js",
    "Go",
    "AWS",
    "Docker",
    "PostgreSQL",
    "Linux",
    "NGINX",
    "WebRTC",
  ],
  keywords: [
    "Andrejs Rinkevičs",
    "System Architect",
    "Full-stack Engineer",
    "Software Engineer",
    "Python",
    "TypeScript",
    "React",
    "Next.js",
    "AWS",
    "Riga",
  ],
} as const
